### ISSUE TITLE
Localisation in pure 2D

### ISSUE THREAD

**Issue by lquinet** [AlexisTM/MultilaterationTDOA#1]
Hi,

If I want to localise in pure 2D, i.e. with the anchors and tag at same height, there are some problems.

First, with solve_2D() method. If we have an anchor with the coordinates (0, 0, 0), the solve_2D() always returns (0, 0, 0) position. **It is due to the jacobian calculation because PA or PB = 0 when last result = (0,0,0). It could be fixed by testing if PA or PB equals 0 and replace it by a smal value,** but I don't know if it is optimum.

```
    def jacobian_2D(self, estimate, measurements, height):
        # According to: https://github.com/AlexisTM/MultilaterationTDOA/blob/master/Algorithmics.md
        jacobian = np.array([0.0, 0.0])
        approx = Point(estimate)
        approx.z = height
        for mea in measurements:
            PA = approx.dist(mea.anchorA)
            PB = approx.dist(mea.anchorB)
            mult = PB-PA-mea.tdoa
            
            # fixing division by 0
            if PA == 0:
                PA = 1e-3
            if PB == 0:
                PB == 1e-3
                
            jacobian[0] += 2*((approx.x-mea.anchorB.position.x)/PB - (approx.x-mea.anchorA.position.x)/PA)*mult
            jacobian[1] += 2*((approx.y-mea.anchorB.position.y)/PB - (approx.y-mea.anchorA.position.y)/PA)*mult
            # Doing it for each member separetely is about ~35% faster
            # j = 2*((approx-mea.anchorB.position)/PB - (approx-mea.anchorA.position)/PA)*(PB-PA-mea.tdoa)
            # jacobian[0] += j.x
            # jacobian[1] += j.y
        return jacobian
```

The second problem is a convergence problem when we are using solve() method with noise. Sometimes when we localise in pure 2D the result doesn't converge at the correct position. Perhaps it is due to a local minimum? The setup used when I have noticed that is

> P = Point((0.5,1,0))
> A0 = Anchor((0,     0,  0))
> A1 = Anchor((1.5,   0,  0))
> A2 = Anchor((0,     2,  0))
> A3 = Anchor((1.5,   2,  0))

**Comment by AlexisTM** [comment]
About the Pure 2D, the solve_2D function is actually a pure 2D problem we are solving. The Z is fixed. It is often called 2.5D by the fact that it can converge to a 3D position using a simplified problem where Z could be another source of data. The solve function is simply not enforcing the Z and should not be used for you.

The division by zero is definitely an issue I did not think about the very small `PA` that would pull jacobians to infinity. I would not do: `if PA == 0:` because it will not catch the "very close to" case.

I would try the following:
- Do not take into account the jacobians where `PA` or `PB` are very small such as `if PA < 0.1: continue`.
- Remove the Jacobian completely, this corner case will not be a problem and it only fastens the convergence of only about 35% but the results in simulation were very similar (~0.01m difference).

Finally, for the convergence, you could put more anchors and with more space in between. Indeed, 4 anchors are only 6 possible combinations. We use at least 6 anchors (Up to 15 combinations).

NOTE: Do you know another optimization library that would allow me to use each measurement individually instead of one optimization function? Indeed, it is hard to reject properly the measurements, and for the next step, rejection of bad measurements is mandatory (computation of X,Y,Theta using 2 tags).

In the following paper, you can see how bad becomes the measurements once you go out of the "convex hull" formed by the anchors: http://mikehamer.info/assets/papers/Ledergerber,%20Hamer,%20DAndrea%20-%20IROS%202015.pdf

![image](https://user-images.githubusercontent.com/6976744/59060820-411cd980-88a2-11e9-87ab-973cbcaad48b.png)

NOTE2: You should not trust "one result", but instead fuse all the results into a Kalman filter such as  `robot_localization`.

**Comment by lquinet** [comment]
By not taking into account the jacobians `if PA < 0.1 or PB < 0.1` doesn't really change in my case. It is not faster (1,8 ms in average) but generate more outliers around the anchors. It generate the same results if the condition is `PA < 1e-3 or PB < 1e-3`. By removing the Jacobian completely the results are the same but a little slower (2,5 ms in average).

Indeed it could be interesting to use more anchors, but for the moment I am limited by 4. Furthermore using 5 anchors would allow to reduce the system to a linear form, according this article: http://files.andersen.im/analytics/Convex%20Optimization%20-%20Comparative%20Analysis%20of%20Multilateration%20Methods%20for%20Signal%20Emitter%20Positioning.pdf .

In fact I am developing a centralised wired-synchronised TDOA architecture, where this is the tag which emits an UWB blink message.

About your note1: I am not really aware of optimization libraries. But to reject the measurements perhaps a first idea would be to estimate the receive signal power and the Standard Deviation of Channel Impulse Response (CIRE) (page 46 of DW1000 USER MANUAL 2.11). I have also found a great library to evaluate Indoor Localization algorithms: https://github.com/pylayers/pylayers .

About your note 2: That's the idea for future development. But do you have an equivalent library in python?

I thank you a lot for your advice. Feel free to contact me at loic.quinet@cerisic.be if you want some collaboration.

**Comment by AlexisTM** [comment]
Dear Loic,

Knowing that you do the opposite (Anchors are receivers, asset tracking), you are looking at a single data emitted at t0 received at multiple points. In our case of (r)TDoA, we have extra noise because we receive multiple non-correlated (at least less) noisy transmissions. You might want to fork as we will not go with the simplifications for asset tracking (I will never have time for that, this repo is basically a side project that aims to be in production later...). Indeed, many companies are providing the Asset tracking capability: Sewio, Pozyx, ... are all focusing on localisation and the asset tracking problem.
If I am not incorrect, you could even consider your problem as ToA due to the fact that you have wired-synchronised anchors. The reason we need TDoA is because no anchor is synchronised in our case for simplicity of deployment and hardware availability (Bitcraze).

Following the [very interesting] article, I believe that you could reduce the system with 4 anchors as you have a fixed Z. (Just a guess).

The next development with N (min 2) tags is in a very unstable state which is partially breaking things and with incomplete documentation, in ~another repo which is private~ [another branch](https://github.com/AlexisTM/MultilaterationTDOA/tree/feature_multiple_receivers). The idea is to do the same optimization problem [x, y, theta], computing the error with the relocated X,Y of the receivers (fixed in the base_link of the AGV). Without noise, this works well, but once I add some noise, the results are 'bad' (at first sight). This implementation has an additional Receiver class that is store in the Engine. When adding a measurement, we specify the receiver. If the receiver is set to None (default), it would solve it for a base_link offset of (0,0,0) effectively giving the same result. Note that this would fail if there is only one tag which is excentered due to the unknown theta.

[Pylayers](http://pylayers.github.io/pylayers/) is awesome. I will look into it whenever I have time [if I do have time -And I didn't have any time, thus not used-].

**Comment by AlexisTM** [comment]
Closing as stale.
